spring:
  profiles:
    active: dev

  freemarker:
#    template-loader-path: file:///D:/test/templates/
    template-loader-path: classpath:/templates/
    cache: false
    suffix: .html

mybatis-plus:
  mapperLocations: classpath:mappers/*.xml

